### ISSUE TITLE
使用分词时符号和数字未分开

### ISSUE THREAD

**Issue by 2han9b1n** [wangshizebin/jiebago#1]
如设备的CPU使用率大于50%       使用分词应该为设备/的/CPU/使用率/大于/50/%        结果为设备/的/CPU/使用率/大于/50%

**Comment by wangshizebin** [comment]
目前的项目中，设定了几个符号，包括 +#&._%- 是要作为普通字符进行处理的，也就是说这几个符号必须跟其它字符结合才有意义。如果有特殊要求需要分开的话，可以修改源码中正则匹配的规则。这个规则在common.go中：
`RegExpText  = "([\u4e00-\u9fa5a-zA-Z0-9+#&._%-])+"`
将其中 % 去掉就可以了。

**Comment by 2han9b1n** [comment]
好的 谢谢
